#!/usr/bin/env python3

# etypography
import etypography
from etypography import FontFace
from etypography import PrimaryAxisTextAlign
from etypography import RichText
from etypography import SecondaryAxisTextAlign
from etypography import layout_text

# click
import click

# emath
from emath import FVector2

# pillow
from PIL import Image
from PIL import ImageDraw

# python
import hashlib
from itertools import product
import json
from pathlib import Path
import shutil

RESOURCE_DIRECTORY = Path(__file__).parent
TEXT_LAYOUT_DIRECTORY = RESOURCE_DIRECTORY / "text-layout"

TEXT = [
    "abcdef",
    "hello\nworld",
    "a b c d e f g",
    "\nhello\nworld\n",
    " \n ",
]
FONT_FILES = ["OpenSans-Regular.ttf"]
FONT_SIZE = [
    ("request_pixel_size", {"height": 12}),
    ("request_pixel_size", {"height": 24}),
]

RICH_TEXT = [
    *(((t, f, m, k),) for t, f, (m, k) in product(TEXT, FONT_FILES, FONT_SIZE)),
    (
        ("hello ", "OpenSans-Regular.ttf", "request_pixel_size", {"height": 12}),
        ("world", "OpenSans-Regular.ttf", "request_pixel_size", {"height": 24}),
    ),
    (
        ("hello ", "OpenSans-Regular.ttf", "request_pixel_size", {"height": 24}),
        ("world", "OpenSans-Regular.ttf", "request_pixel_size", {"height": 12}),
    ),
]

BREAK_TEXT = ["break_text_icu_line", "break_text_never"]
MAX_LINE_SIZE = [None, 32, 99999]
LINE_HEIGHT = [None, 32]
IMAGE_SIZE = 512
HALF_IMAGE_SIZE = IMAGE_SIZE / 2


@click.command()
def main():
    shutil.rmtree(TEXT_LAYOUT_DIRECTORY)
    TEXT_LAYOUT_DIRECTORY.mkdir()

    for (
        rich_text_params,
        break_text_name,
        max_line_size,
        p_align,
        s_align,
        line_height,
    ) in product(
        RICH_TEXT,
        BREAK_TEXT,
        MAX_LINE_SIZE,
        PrimaryAxisTextAlign,
        SecondaryAxisTextAlign,
        LINE_HEIGHT,
    ):
        sha256 = hashlib.sha256()
        for text, font, font_size_method_name, font_size_kwargs in rich_text_params:
            sha256.update(text.encode("utf8"))
            sha256.update(font.encode("utf8"))
            sha256.update(font_size_method_name.encode("utf8"))
            sha256.update(str(font_size_kwargs).encode("utf8"))
        sha256.update(break_text_name.encode("utf8"))
        sha256.update(str(max_line_size).encode("utf8"))
        sha256.update(p_align.encode("utf8"))
        sha256.update(s_align.encode("utf8"))
        sha256.update(str(line_height).encode("utf8"))
        name = sha256.hexdigest()

        rich_text = []
        for text, font, font_size_method_name, font_size_kwargs in rich_text_params:
            with open(RESOURCE_DIRECTORY / font, "rb") as font_file:
                font_face = FontFace(font_file)
            font_face_method = getattr(font_face, font_size_method_name)
            font_face_size = font_face_method(**font_size_kwargs)
            rich_text.append(RichText(text, font_face_size))

        break_text = getattr(etypography, break_text_name)
        text_layout = layout_text(
            rich_text,
            primary_axis_alignment=p_align,
            secondary_axis_alignment=s_align,
            max_line_size=max_line_size,
            break_text=break_text,
            origin=FVector2(HALF_IMAGE_SIZE),
            line_height=line_height,
        )

        image = Image.new(mode="RGB", size=(IMAGE_SIZE, IMAGE_SIZE))
        draw = ImageDraw.Draw(image)
        draw.line((HALF_IMAGE_SIZE, 0, HALF_IMAGE_SIZE, IMAGE_SIZE), width=1)
        draw.line((0, HALF_IMAGE_SIZE, IMAGE_SIZE, HALF_IMAGE_SIZE), width=1)

        if text_layout is not None:
            for text_glyph in text_layout.glyphs:
                font_face_size = text_glyph.font_face_size
                face = font_face_size.face
                rendered_glyph = face.render_glyph(text_glyph.glyph_index, font_face_size)
                image_glyph = Image.frombytes("L", tuple(rendered_glyph.size), rendered_glyph.data)
                image.paste(
                    image_glyph,
                    tuple(
                        round(d)
                        for d in (text_glyph.bounding_box.position + rendered_glyph.bearing)
                    ),
                )

            for line in text_layout.lines:
                draw.rectangle(
                    (
                        round(line.bounding_box.position.x),
                        round(line.bounding_box.position.y),
                        round(line.bounding_box.extent.x),
                        round(line.bounding_box.extent.y),
                    ),
                    outline="red",
                    width=2,
                )

            draw.rectangle(
                (
                    round(text_layout.bounding_box.position.x),
                    round(text_layout.bounding_box.position.y),
                    round(text_layout.bounding_box.extent.x),
                    round(text_layout.bounding_box.extent.y),
                ),
                outline="green",
            )

        data = {
            "rich_text": [
                {
                    "text": t,
                    "size": {
                        "font": f,
                        "method": m,
                        "kwargs": k,
                    },
                }
                for t, f, m, k in rich_text_params
            ],
            "layout_text_kwargs": {
                "primary_axis_alignment": p_align,
                "secondary_axis_alignment": s_align,
                "break_text": break_text_name,
                "max_line_size": max_line_size,
                "line_height": line_height,
            },
            "text_layout": {
                "position": tuple(text_layout.bounding_box.position),
                "size": tuple(text_layout.bounding_box.size),
                "lines": [
                    {
                        "position": tuple(line.bounding_box.position),
                        "size": tuple(line.bounding_box.size),
                        "glyphs": [
                            {
                                "character": glyph.character,
                                "glyph_index": glyph.glyph_index,
                                "position": tuple(glyph.bounding_box.position),
                                "size": tuple(glyph.bounding_box.size),
                                "font_face_size": repr(glyph.font_face_size),
                            }
                            for glyph in line.glyphs
                        ],
                    }
                    for line in text_layout.lines
                ],
            }
            if text_layout
            else None,
        }
        image.save(TEXT_LAYOUT_DIRECTORY / f"{name}.png")
        with open(TEXT_LAYOUT_DIRECTORY / f"{name}.json", "w", encoding="utf8") as f:
            json.dump(data, f, indent="    ")


if __name__ == "__main__":
    main()
